// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.ts";
import type { HookEventName } from "./HookEventName.ts";
import type { HookExecutionMode } from "./HookExecutionMode.ts";
import type { HookHandlerType } from "./HookHandlerType.ts";
import type { HookOutputEntry } from "./HookOutputEntry.ts";
import type { HookRunStatus } from "./HookRunStatus.ts";
import type { HookScope } from "./HookScope.ts";
import type { HookSource } from "./HookSource.ts";
export type HookRunSummary = { id: string, eventName: HookEventName, handlerType: HookHandlerType, executionMode: HookExecutionMode, scope: HookScope, sourcePath: AbsolutePathBuf, source: HookSource, displayOrder: bigint, status: HookRunStatus, statusMessage: string | null, startedAt: bigint, completedAt: bigint | null, durationMs: bigint | null, entries: Array<HookOutputEntry>, };
