// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpElicitationBooleanSchema } from "./McpElicitationBooleanSchema.ts";
import type { McpElicitationEnumSchema } from "./McpElicitationEnumSchema.ts";
import type { McpElicitationNumberSchema } from "./McpElicitationNumberSchema.ts";
import type { McpElicitationStringSchema } from "./McpElicitationStringSchema.ts";
export type McpElicitationPrimitiveSchema = McpElicitationEnumSchema | McpElicitationStringSchema | McpElicitationNumberSchema | McpElicitationBooleanSchema;
