// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanType } from "../PlanType.ts";
import type { CreditsSnapshot } from "./CreditsSnapshot.ts";
import type { RateLimitReachedType } from "./RateLimitReachedType.ts";
import type { RateLimitWindow } from "./RateLimitWindow.ts";
import type { SpendControlLimitSnapshot } from "./SpendControlLimitSnapshot.ts";
export type RateLimitSnapshot = { limitId: string | null, limitName: string | null,
/**
 * Normal model whose display name and reasoning options describe this quota alias.
 */
normalModelSlug: string | null, primary: RateLimitWindow | null, secondary: RateLimitWindow | null, credits: CreditsSnapshot | null, individualLimit: SpendControlLimitSnapshot | null,
/**
 * Backend-reported spend-control state. `None` is unavailable, not a sparse-update recovery.
 */
spendControlReached: boolean | null, planType: PlanType | null, rateLimitReachedType: RateLimitReachedType | null, };
