// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality.ts";
import type { JsonValue } from "../serde_json/JsonValue.ts";
import type { ApprovalsReviewer } from "./ApprovalsReviewer.ts";
import type { AskForApproval } from "./AskForApproval.ts";
import type { SandboxMode } from "./SandboxMode.ts";
import type { ThreadSource } from "./ThreadSource.ts";
import type { ThreadStartSource } from "./ThreadStartSource.ts";
export type ThreadStartParams = {model?: string | null, modelProvider?: string | null, serviceTier?: string | null | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, /**
 * Override where approval requests are routed for review on this thread
 * and subsequent turns.
 */
approvalsReviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, serviceName?: string | null, baseInstructions?: string | null, developerInstructions?: string | null, /**
 * @deprecated `friendly` and `pragmatic` no longer select a style.
 */
personality?: Personality | null, ephemeral?: boolean | null, sessionStartSource?: ThreadStartSource | null, /**
 * Optional client-supplied analytics source classification for this thread.
 */
threadSource?: ThreadSource | null};
