// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.ts";
import type { CollaborationMode } from "../CollaborationMode.ts";
import type { Personality } from "../Personality.ts";
import type { ReasoningEffort } from "../ReasoningEffort.ts";
import type { ReasoningSummary } from "../ReasoningSummary.ts";
import type { ActivePermissionProfile } from "./ActivePermissionProfile.ts";
import type { ApprovalsReviewer } from "./ApprovalsReviewer.ts";
import type { AskForApproval } from "./AskForApproval.ts";
import type { SandboxPolicy } from "./SandboxPolicy.ts";
export type ThreadSettings = {/**
 * Saved list of disabled plugin IDs. Does not yet filter plugin capabilities.
 */
disabledPluginIds: Array<string>, cwd: AbsolutePathBuf, approvalPolicy: AskForApproval, approvalsReviewer: ApprovalsReviewer, sandboxPolicy: SandboxPolicy, activePermissionProfile: ActivePermissionProfile | null, model: string, modelProvider: string, serviceTier: string | null, effort: ReasoningEffort | null, summary: ReasoningSummary | null, collaborationMode: CollaborationMode, /**
 * @deprecated Reports the saved setting; `friendly` and `pragmatic` no longer select a style.
 */
personality: Personality | null};
